version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:00"
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      time: "05:00"
