site_name: balaboba
repo_url: https://github.com/monosans/balaboba
repo_name: monosans/balaboba
edit_uri: edit/main/docs/
nav:
  - index.md
  - install.md
  - api.md
theme:
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.footer
    - navigation.top
    - toc.follow
  font: false
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb-outline
        name: Light mode
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/monosans
      name: Developer's Telegram
    - icon: fontawesome/brands/vk
      link: https://vk.com/id607137534
      name: Developer's VK
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/monosans
      name: Developer's LinkedIn
markdown_extensions:
  - pymdownx.superfences
  - toc:
      permalink: true
plugins:
  - search
  - minify_html
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            filters:
              - "!^_(?:[^_].*[^_]|_(?:all|doc|main|module|new|slots)__)$"
            inherited_members: true
            load_external_modules: true
            members_order: source
            merge_init_into_class: true
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_source: false
            show_submodules: true
